### PR TITLE
Issue #23

### PR DESCRIPTION
**Pull request by jffaria**
Test HTTP_HOST to avoid undefined index notice.

### CODE REVIEW

**Comment by jffaria** [comment]
Fixes #23

**Comment by straube** [comment]
Nice catch!

**Comment by straube** [comment]
BTW, do you have a WP.org user? I'll be glad to add your username to the contributors' list.

**Comment by jffaria** [comment]
Hello. Yes, I do, also jffaria over there: https://profiles.wordpress.org/jffaria
I am new to the community though so there is not much in my profile, I will at least update with my name :)
Many thanks for accepting the pull and kindly offering to add to contributors' list.

**Pull request merged**
